require: rubocop-rails
require: rubocop-rspec

AllCops:
  Exclude:
    - 'bin/bundle'
    - 'test/**/*'
    - 'db/schema.rb'

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'db/**/*'

Style/Documentation:
  Enabled: false
